DropDownList/Models/ImagenModelo.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace DropDownList.Models
{
    public class ImagenModelo
    {
        public int IdImagen { get; set; }
        public string NombreFoto { get; set; }
        public string FotoRecuperacion { get; set; }
    }
}

DropDownList/Models/PaisesEstadosModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace DropDownList.Models
{
    public class PaisesEstadosModel
    {
        public int IdPais { get; set; }
        public int IdEstado { get; set; }
      
    }
}

DropDownList/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;


namespace DropDownList.Controllers
{
    public class HomeController : Controller
    {

        EF.PaisesEntities db = new EF.PaisesEntities();
        public ActionResult Index()
        {
            List<EF.Paises> PaisesList = db.Paises.ToList();
            ViewBag.PaisesList = new SelectList(PaisesList, "IdPais", "Pais");
            return View();
        }

        public JsonResult GetEstados(int IdPais)
        {
            db.Configuration.ProxyCreationEnabled = false;
            List<EF.Estados> EstadosList = db.Estados.Where(x => x.IdPais == IdPais).ToList();
            return Json(EstadosList, JsonRequestBehavior.AllowGet);
        }
        
    }
}

DropDownList/Controllers/ImagenController.cs
using EF;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DropDownList.Controllers
{
    public class ImagenController : Controller
    {
        // GET: Imagen
        public ActionResult AgregarImagen()
        {
            return View();
        }

        public ActionResult Guardar(Models.ImagenModelo modelo, HttpPostedFileBase foto)
        {
            if(!ModelState.IsValid || (foto == null && modelo.IdImagen == 0))
            {
                byte[] fotoDB = null;
                if(foto != null)
                {
                    BinaryReader lector = new BinaryReader(foto.InputStream);
                    fotoDB = lector.ReadBytes((int)foto.ContentLength);
                }
                //conexion
                using(var bd = new EF.PaisesEntities())
                {
                    Imagenes imagenes = new Imagenes();
                    imagenes.IdImagen = modelo.IdImagen;
                    imagenes.NombreFoto = modelo.NombreFoto;
                    imagenes.FOTO = fotoDB;
                    bd.Imagenes.Add(imagenes);
                    int res = bd.SaveChanges();
                    if (res == 1)
                    {
                        ViewBag.Message = "La imagen se subio correctamente";
                    }
                    else
                    {
                        ViewBag.Message = "La imagen no se subio correctamente :(";
                    }
                }
            }
            return PartialView("validacion");
        }
    }
}

DropDownList/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

DropDownList/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

DropDownList/Views/Home/Index.cshtml
@model DropDownList.Models.PaisesEstadosModel
@{
    ViewBag.Title = "Home Page";
}

<div class="container">
    <div class="row" style="margin-top: 2em;">
        <div class="form-group">
            <label>Selecciona un pais</label>
            @if (ViewBag.PaisesList != null)
            {
                @Html.DropDownListFor(model => model.IdPais, ViewBag.PaisesList as SelectList, "--Seleccione--", new { @class = "form-control" })
            }
        </div>
        <div class="form-group">
            <label>Selecciona un estado</label>
            @Html.DropDownListFor(model => model.IdEstado, new SelectList(""), "--Seleccione Estado--", new { @class = "form-control" })
        </div>
    </div>
</div>
<script src="~/Scripts/jquery-3.4.1.min.js"></script>
<script>
    $(document).ready(function () {
        $("#IdPais").change(function () {
            $.get("/Home/GetEstados", { IdPais: $("#IdPais").val() }
                ,
                function (data) {
                    $("#IdEstado").empty();
                    $.each(data, function (index, row) {
                        $("#IdEstado").append("<option value='"+row.IdEstado+"'>"+row.Estado+"</option>")
                    });
                });
        })
    })
</script>

DropDownList/Views/Imagen/AgregarImagen.cshtml
@model DropDownList.Models.ImagenModelo
@{
    ViewBag.Title = "AgregarImagen";
}

<h2>AgregarImagen</h2>

@using(Html.BeginForm("Guardar", "Imagen", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
<div class="form-horizontal">
    <div class="form-group">
        <div class="col-md-3">
            @Html.LabelFor(model => model.IdImagen);
            @Html.TextBoxFor(model => model.IdImagen, new { @class = "form-control hidden" })
        </div>
    </div>
    <div class="form-group">
        <div class="col-md-3">
            @Html.LabelFor(model => model.NombreFoto);
            @Html.TextBoxFor(model => model.NombreFoto, new { @class = "form-control" })
        </div>
    </div>
    <div class="form-group">
        <div class="col-md-3">
            <label>Foto</label>
            @Html.Label("Foto");
            <img width="200" height="200" id="imgFoto" style="display:block; margin: 1rem;" />
            @Html.TextBox("foto", "", new { type = "file", id = "fupFoto" })
        </div>
    </div>
    <div class="form-group">
        <button type="button" id="btnClose" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <button type="submit" class="btn btn-primary">Guardar</button>
    </div>
</div>
}
<script src="~/Scripts/jquery-3.4.1.min.js"></script>
<script>
    var imgFoto = document.getElementById("imgFoto");
    var fupFoto = document.getElementById("fupFoto");
    fupFoto.onchange = function () {
        var files = fupFoto.files[0];
        var reader = new FileReader();
        reader.onloadend = function () {
            imgFoto.src = reader.result;
            document.getElementById("nombreFoto").value = files.name;
        }

        reader.readAsDataURL(files);
    }
</script>

DropDownList/Views/Imagen/validacion.cshtml
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
<link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
<script src="http://bootboxjs.com/bootbox.js"></script>
<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">

<div class="modal" tabindex="-1" role="dialog" id="modalValidacion">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">Aviso</h4>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <h5>@ViewBag.Message</h5>
            </div>
            <div class="modal-footer">
                @Html.ActionLink("Regresar", "AgregarImagen", "Imagen", htmlAttributes: new { @class = "btn btn-md-danger" })
            </div>
        </div>
    </div>
</div>

<script>
    $('#modalValidacion').modal();
</script>

DropDownList/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Mi aplicación ASP.NET</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Nombre de la aplicación", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Combobox en cascada", "Index", "Home")</li>
                    <li>@Html.ActionLink("Imagen", "AgregarImagen", "Imagen")</li>
                    <li>@Html.ActionLink("Contacto", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Mi aplicación ASP.NET</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>